//
//  PubNotifition.h
//  LePats
//
//  Created by xiongchi on 15-5-16.
//  Copyright (c) 2015年 admin. All rights reserved.
//

#ifndef LePats_PubNotifition_h
#define LePats_PubNotifition_h

#define MESSAGE_LOGIN_SUC_VC   @"MESSAGE_LOGIN_SUC_VC"

#define MESSAGE_REG_SUC_VC  @"MESSAGE_REG_SUC_VC"

#define MESSAGE_UPDATE_USER_VC @"MESSAGE_UPDATE_USER_VC"

#define MESSAGE_UPDATE_USER_T_VC @"MESSAGE_UPDATE_USER_T_VC"

#define MESSAGE_UPDATE_USER_TH_VC @"MESSAGE_UPDATE_USER_TH_VC"

#define MESSAGE_SHOW_LOGIN_VC @"MESSAGE_SHOW_LOGIN_VC"

#define  MESSAGE_SHOW_MAIN_VC @"MESSAGE_SHOW_MAIN_VC"

#define MESSAGE_FOR_KEYBOARD_INFO @"MESSAGE_FOR_KEYBOARD_INFO"

#define MESSAGE_FOR_RESUME_UPDATE_VC   @"MESSAGE_FOR_RESUME_UPDATE_VC"

#define MESSAGE_FOR_EVALUTION_VC  @"MESSAGE_FOR_EVALUTION_VC"

#define MESSAGE_FOR_STUHOR_VC @"MESSAGE_FOR_STUHOR_VC"

#define MESSAGE_FOR_TRUEJOB_VC  @"MESSAGE_FOR_TRUEJOB_VC"

#define MESSAGE_FOR_PEIXUN_VC  @"MESSAGE_FOR_PEIXUN_VC"

#define MESSAGE_FOR_LANGUGE_VC  @"MESSAGE_FOR_LANGUGE_VC"

#define MESSAGE_FOR_TRAIN_VC  @"MESSAGE_FOR_TRAIN_VC"

#define MESSAGE_FOR_ADD_BBS_VS @"MESSAGE_FOR_ADD_BBS_VS"

#define MESSAGE_FOR_ADD_TEACH_VS @"MESSAGE_FOR_ADD_TEACH_VS"

#define NS_UPDATE_USER_INFO_VC @"NS_UPDATE_USER_INFO_VC"

#define MESSAGE_FOR_UPDATE_USER_INFO @"MESSAGE_FOR_UPDATE_USER_INFO"


#endif
